# -*- coding: utf-8 -*-
"""Ejercicio con multiprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_cajVbHSzVlOp16wKo1ZuQvusLWsYxk
"""

import multiprocessing
import math

def calcular_factorial(numero):
    resultado = math.factorial(numero)
    print(f"El factorial de {numero} es {resultado}")
    return resultado

if __name__ == '__main__':
    numeros = [100000 + x for x in range(5)] # Lista de cinco números grandes
    with multiprocessing.Pool(processes=5) as pool:
        resultados = pool.map(calcular_factorial, numeros)

    print("Resultados:", resultados)

